### ISSUE TITLE
end_date query parameter 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rides-blueprint#14]
When we query end_date as 2021-02-14 the timestamp is transformer to start of day as '2021-02-14 00:00:00.000000'. I think this way we will miss a ride that starts for example at 9:00 am on 2021-02-14. For end date we need to be converting the date string to `2021-02-14 23:59:59`.

Ideally we need a test that fails that shows a problem and and a fix, something like `def convert_end_date(end_date: str)`.

**Comment by epogrebnyak** [comment]
Also consider a case where start_date == end_date, this will alsways return empty selection in our current implementation and we want exactly one day.

**Comment by epogrebnyak** [comment]
Points were end_date is used: https://github.com/epogrebnyak/rides-blueprint/search?q=end_date

**Comment by epogrebnyak** [comment]
@yuanshoujing - after fixing stuff please provide code for review. Things I look for:

- [ ] the test that shows something has to be fixed, not working
- [ ] the code added that makes a test pass
- [ ] additional tests that test new functionality

**Comment by yuanshoujing** [comment]
> the test that shows something has to be fixed, not working

@epogrebnyak  Could you be a little more specific?
