### ISSUE TITLE
make new command approx_tracks(db_url, step_km)

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rides-blueprint#35]
in query_metrics:

```
def approx_tracks(db_url, step_km):
    # calculate approximated tracks for all tracks in jsondata 
    # write approximation of track to simplified_tracks table as JSON
    # calculate lengths 

    # for every raw track:
    ts = approximate(t, step_km)
    # save ts with waybill to simplified_tracks 
    m = mileage(ts)
    # save ts with waybill
```
    
Provide functions to retrieve:

```
def read_length(engine, waybill_id):
  pass

def read_simplified_track(engine, waybill_id):
  pass
```

**Comment by epogrebnyak** [comment]
After we are done with `approx_tracks()` we can change `import_jsons()` is that:
- `import_jsons()`  accepts step_km parameter
- `import_jsons()` call `import_json()` on every file 
- `import_json()` does three things: 
   - write row to jsondata  table
   - calculate simplified track and write it in simplified_tracks table
   - claculate lengths and write into length table

**Comment by epogrebnyak** [comment]
So on calling import_jsons() we will have a guarantee that lengths and simplied tracks are calculated. 

`approx_tracks()` can be used is someone wants to change the `step_km` parameter.

On fine-tuning we may also write `step_km` to `simplified_tracks` table. 

Maybe  call simplified_tracks `simtracks` for short?

**Comment by yuanshoujing** [comment]
The problem should have been fixed.

**Comment by epogrebnyak** [comment]
> The problem should have been fixed.

@yuanshoujing - this is not a problem, this is new feature :)

**Comment by epogrebnyak** [comment]
@yuanshoujing  - approx_tracks was refactoered in transition.py - please make it work there and adjust tests accordingly.
