### ISSUE TITLE
Update existing information test fails

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rides-blueprint#36]
Name of test: test_save_convergence_must_update_existing_information

**Comment by epogrebnyak** [comment]
I think @qangdev  fialed the test while changing parameters in #4:

```
    min_cov_1=0.5,
    min_cov_2=0.3
```

param_dict_1 = dict(
    region_name="volga",
    customer_id="ef8c0f17-419d-11e5-80bc-1cc1de769e18",
    start_date="2021-02-08",
    end_date="2021-02-14",
    min_cov_1=0.5,
    min_cov_2=0.3
)

**Comment by epogrebnyak** [comment]
The way forward is to use param_dict_1 and param_dict_1  for different pars of test

**Comment by yuanshoujing** [comment]
Before logic.py::filter_out_metrics, the dataframe looked like this:

`
                              waybill_1                             waybill_2  min_dist  ...  len_2  cov_1 cov_2
1  f3fd8518-6c60-11eb-914f-c4346bc03f7c  054078a7-6d2c-11eb-914f-c4346bc03f7c     0.013  ...   89.3   0.44  0.38
2  736f0239-6c69-11eb-914f-c4346bc03f7c  468073e7-6a04-11eb-914f-c4346bc03f7c     0.038  ...  373.8   1.00  0.36
0  f3fd8518-6c60-11eb-914f-c4346bc03f7c  f887a1a9-6d2b-11eb-914f-c4346bc03f7c     0.010  ...  179.7   0.61  0.27
`

The test case is to find min_cov_1=0.5 and min_cov_2=0.3, so after filtering logic.py::filter_out_metrics, there is only one left that satisfies the criteria:

`
                              waybill_1                             waybill_2  min_dist  ...  len_2  cov_1 cov_2
2  736f0239-6c69-11eb-914f-c4346bc03f7c  468073e7-6a04-11eb-914f-c4346bc03f7c     0.038  ...  373.8    1.0  0.36
`

So the assert is no longer true.
