### ISSUE TITLE
deploying to remote server

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rides-blueprint#6]
Our database and python application should be working on a remote server. 

On that server we shall need Postgres, python3 

The database manager (a person) will upload most recent JSON files weekly to raw database. Maybe the admins can set a cron job for that.

The manager will also invoke a data analysis pipeline that will save the computation results to metrics database. The pipeline can run for quite long time, about 1 hour for 1 week of data.

There is also a script that can query the metrics db and provide metrics by customer (company). That script is exposed via REST API - maybe through flask or FastAPI.

What should we ask for on server side and what kind of deployment shall we use to make this server running?

**Comment by yuanshoujing** [comment]
@epogrebnyak I have modified the previous comments, please see if there are any other details that need to be added.
